### ISSUE TITLE
spring-data-commons reference/api link missing from spring.io site for spring-data - http://projects.spring.io/spring-data/

### ISSUE THREAD

**Issue by bijukunjummen** [spring-projects/spring-data#40]
Hi, The Spring-data-commons related api/reference link appears to be missing from the spring.io site for spring-data here -  http://projects.spring.io/spring-data/. The only way appears to be to go google for spring-data-commons and find it that way(https://github.com/spring-projects/spring-data-commons).

I may be missing something in the way I am searching for this reference, but just wanted to open an issue in case this is really being missed from the spring-data pages.

**Comment by olivergierke** [comment]
Spring Data Commons is not a module to be used on its own. That's why it doesn't have a dedicated project page.
