### ISSUE TITLE
validation doesn't throw 400

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-data#41]
not sure if this is the right spot for bugs in -rest/-jpa

I created an app (documented here http://www.xenoterracide.com/2014/09/using-spring-to-create-full-rest-api-in.html), I can probably give a normal repo if that's really necessary, but it's basically the same as  http://spring.io/guides/gs/accessing-data-rest/ example application, except a different Entity. The problem I've noticed is that when a my entity fails validation, like making `"description" : ""` instead of throwing a 400 I get a 500 with a transaction error, internally the constraint violations are printed in the log.

**Comment by olivergierke** [comment]
Please raise issues for Spring Data Commons in [JIRA](https://jira.spring.io/browse/DATAREST).
