### ISSUE TITLE
DomainClassConverter double conversion

### ISSUE THREAD

**Issue by tifoha** [spring-projects/spring-data#43]
Hi! I am trying to use Spring's DomainClassConverter feature with my Spring MVC project. But I got a problem with my controllers.
The problem is that I can not get the changed values of the form  to ModelAttribute.
For example: i have object User{id: 1, username: "user", pass: "111"} in my database, when i try to modify it into form end post changes(User{id: 1, username: "user_changed", pass: "222"}) to controller, i receive the persistent User(without changes)

``` java
    @RequestMapping(method = RequestMethod.POST)
    public ModelAndView create(@ModelAttribute("user") @Valid User user,
                               BindingResult bindingResultUser,
                               ModelAndView model,
                               WebRequest webRequest,
                               Locale locale) {...}
```

After some time spent debugging,  i find the reason of such converter behavior.

first starts from this row when ModelAttributeMethodProcessor try to convert bound user object to ModelAttribute: **return binder.convertIfNecessary(binder.getTarget(), parameter.getParameterType(), parameter);**

```
@Override
	public final Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
			NativeWebRequest webRequest, WebDataBinderFactory binderFactory) throws Exception {

		String name = ModelFactory.getNameForParameter(parameter);
		Object attribute = (mavContainer.containsAttribute(name) ?
				mavContainer.getModel().get(name) : createAttribute(name, parameter, binderFactory, webRequest));

		WebDataBinder binder = binderFactory.createBinder(webRequest, attribute, name);
		if (binder.getTarget() != null) {
			bindRequestParameters(binder, webRequest);
			validateIfApplicable(binder, parameter);
			if (binder.getBindingResult().hasErrors() && isBindExceptionRequired(binder, parameter)) {
				throw new BindException(binder.getBindingResult());
			}
		}

		// Add resolved attribute and BindingResult at the end of the model
		Map<String, Object> bindingResultModel = binder.getBindingResult().getModel();
		mavContainer.removeAttributes(bindingResultModel);
		mavContainer.addAllAttributes(bindingResultModel);

		return binder.convertIfNecessary(binder.getTarget(), parameter.getParameterType(), parameter);
	}
```

Then, DataBinder-> invoke the ConversionService->DomainClassConverter to convert User object to convert it into ModelAttribute.
DomainConverter first converts User->Id, then back in User, at this moment User is re-reading from the database and lost all modified assignments that DataBinder made.

I solve this problem when i replaced this row ~~if (sourceType.equals(targetType)) {~~ to **if (sourceType.getType() != null && sourceType.getType().equals(targetType.getType())) {**

in theory we have to compare types but TypeDescriptors.

Can you fix this problem in next releases?
```java
		@Override
		public Object convert(Object source, TypeDescriptor sourceType, TypeDescriptor targetType) {

			if (source == null || !StringUtils.hasText(source.toString())) {
				return null;
			}

			if (sourceType.equals(targetType)) {
				return source;
			}

			Class<?> domainType = sourceType.getType();

			EntityInformation<Object, ?> entityInformation = repositories.getEntityInformationFor(domainType);

			return conversionService.convert(entityInformation.getId(source), targetType.getType());
		}
```

**Comment by olivergierke** [comment]
Please raise issues for Spring Data Commons in [JIRA](https://jira.spring.io/browse/DATACMNS).
